### ISSUE TITLE
Unexpected end of JSON input while parsing near '...gPoeliBpeotSxNjNkg5Bv'

### ISSUE THREAD

**Issue by nythma** [VicenLaw/vue-antd-pro#1]
npm install 出现Unexpected end of JSON input while parsing near '...gPoeliBpeotSxNjNkg5Bv'

**Comment by VicenLaw** [comment]
终止后继续安装，是可以正常运行的。也可以尝试下以下命令。

npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
